version: "3.8"
services:
  api-gateway:
    image: api-gateway
    container_name: api-gateway
    build:
      context: ../.
      dockerfile: ./api-gateway/Dockerfile
    environment:
      - HOST=host.docker.internal
    ports:
      - "8080:8080"