version: "3.8"
services:
  api-gateway:
    image: api-gateway
    container_name: api-gateway
    build:
      context: ../.
      dockerfile: ./api-gateway/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"