version: "3.8"
services:
  discovery-server:
    image: discovery-server
    container_name: discovery-server
    build:
      context: ../.
      dockerfile: ./discovery-server/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8761:8761"