HOST: localhost
RABBITMQ_USERNAME: guest
RABBITMQ_PASSWORD: guest
range:
  startAdder: 1
  endAdder: 3000

server:
  port: 8083

spring:
  application:
    name: range-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  config:
    import: optional:configserver:http://${HOST}:8888/
  rabbitmq:
    host: ${HOST}
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/url_shortener?serverTimezone=UTC
    username: range_app
    password: p_range_app

eureka:
  client:
    serviceUrl:
      defaultZone: http://${HOST}:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: httptrace, prometheus
  endpoint:
    health:
      show-details: ALWAYS
  zipkin:
    tracing:
      endpoint: http://${HOST}:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  info:
    env:
      enabled: true