version: "3.8"
services:
  db:
    image: mysql:8.0.28
    cap_add:
      - SYS_NICE
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: url_shortener
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  range-service:
    image: range-service
    container_name: range-service
    build:
      context: ../.
      dockerfile: ./range-service/Dockerfile
    restart: unless-stopped
    ports:
      - "5200-5210:8083"
    depends_on:
      - db

volumes:
  db:
    driver: local