global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 15s
    static_configs:
      - targets: [ "localhost:9090" ]
  - job_name: "node"
    static_configs:
      - targets: [ "node-exporter:9100" ]

  - job_name: 'url-shortener-service'
    scrape_interval: 15s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:5100', 'host.docker.internal:5101', 'host.docker.internal:5102', 'host.docker.internal:5103']
        labels:
          application: 'Url shortener application'
  - job_name: 'range-service'
    scrape_interval: 15s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:5200', 'host.docker.internal:5201', 'host.docker.internal:5202', 'host.docker.internal:5203']
        labels:
          application: 'Range service application'
  - job_name: 'api-gateway'
    scrape_interval: 15s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'Api gateway application'
  - job_name: 'config-server'
    scrape_interval: 15s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8888' ]
        labels:
          application: 'Config server'
  - job_name: 'discovery-server'
    scrape_interval: 15s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8761' ]
        labels:
          application: 'Eureka server'