HOST: localhost

server:
  port: 8761

spring:
  application:
    name: discovery-server
  cloud:
    config:
      enabled: false

eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${HOST}:${server.port}/eureka

management:
  endpoints:
    web:
      exposure:
        include: httptrace, prometheus
  endpoint:
    health:
      show-details: ALWAYS
  zipkin:
    tracing:
      endpoint: http://${HOST}:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  info:
    env:
      enabled: true