HOST: localhost
RABBITMQ_USERNAME: guest
RABBITMQ_PASSWORD: guest
MONGODB_USERNAME: rootuser
MONGODB_PASSWORD: rootpass

server:
  port: 8082

spring:
  application:
    name: url-shortener-service
  servlet:
    context-path: "/${spring.application.api-version}"
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  config:
    import: optional:configserver:http://${HOST}:8888/
  rabbitmq:
    host: ${HOST}
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: urlshortener
      port: 27017
      host: ${HOST}
      auto-index-creation: true
    redis:
      host: ${HOST}
      port: 6379
  cache:
    type: redis

eureka:
  client:
    serviceUrl:
      defaultZone: http://${HOST}:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: httptrace, prometheus
  endpoint:
    health:
      show-details: ALWAYS
  zipkin:
    tracing:
      endpoint: http://${HOST}:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  info:
    env:
      enabled: true