HOST: localhost

server:
  port: 5100

spring:
  application:
    name: url-shortener-service
  config:
    import: optional:configserver:http://${HOST}:8888/
  rabbitmq:
    host: ${HOST}
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: urlshortener
      port: 27017
      host: ${HOST}
      auto-index-creation: true
    redis:
      host: ${HOST}
      port: 6379
  cache:
    type: redis

eureka:
  client:
    serviceUrl:
      defaultZone: http://${HOST}:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: httptrace, prometheus, busrefresh, busenv
  endpoint:
    health:
      show-details: ALWAYS
  zipkin:
    tracing:
      endpoint: http://${HOST}:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  info:
    env:
      enabled: true