HOST: localhost

server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          uri: https://github.com/baakapps/cfg.git
          default-label: master
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: false
  rabbitmq:
    host: ${HOST}
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${HOST}:${server.port}/eureka

management:
  endpoints:
    web:
      exposure:
        include: httptrace, prometheus, busrefresh
  endpoint:
    health:
      show-details: ALWAYS
  zipkin:
    tracing:
      endpoint: http://${HOST}:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  info:
    env:
      enabled: true