version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/docker
    user: root
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock.raw:/var/run/docker.sock
    networks:
      - net
networks:
  net: