pipeline {
    agent any

    parameters {
        booleanParam(name: 'runAllServices', defaultValue: true, description: 'Whether to run all services or select some of them')
        choice(name: 'selectedServices', choices: ['api-gateway', 'config-server', 'discovery-server', 'range-service', 'url-shortener-service'], description: 'Select the services to run', multiSelect: true, filterable: true)
    }

    stages {
        stage('Build') {
            when {
                expression { params.runAllServices == true || params.selectedServices }
            }
            steps {
                script {
                    def servicesToRun = []
                    if (params.runAllServices == true) {
                        servicesToRun = ['api-gateway', 'config-server', 'discovery-server', 'range-service', 'url-shortener-service']
                    } else {
                        servicesToRun = params.selectedServices
                    }

                    for (service in servicesToRun) {
                        sh "cd ${service} && mvn clean package &"
                    }

                    // Wait for all services to start up
                    sh 'sleep 30'
                }
            }
        }
    }
}
